# Generated by Django 4.1.6 on 2023-02-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.CharField(max_length=1000)),
                ('To', models.CharField(max_length=1000)),
                ('Mobile', models.CharField(max_length=1000)),
                ('Date', models.DateField()),
                ('Gender', models.BooleanField()),
            ],
        ),
    ]
