# Generated by Django 4.1.6 on 2023-02-27 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='From',
            new_name='From_location',
        ),
        migrations.RenameField(
            model_name='userdetails',
            old_name='To',
            new_name='To_location',
        ),
    ]
