# Generated by Django 4.1.6 on 2023-02-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainApp', '0002_rename_from_userdetails_from_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1),
        ),
    ]
