# Generated by Django 4.1.6 on 2023-02-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainApp', '0003_alter_userdetails_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='From_location',
            field=models.CharField(choices=[('HYD', 'Hyderabad'), ('MB', 'Mumbai'), ('TN', 'Tamil Nadu')], max_length=3),
        ),
    ]
