# Generated by Django 4.1.6 on 2023-02-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainApp', '0004_alter_userdetails_from_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='From_location',
            field=models.CharField(choices=[('HYD', 'Hyderabad'), ('MB', 'Mumbai'), ('T', 'Tirupati'), ('ND', 'New Delhi'), ('TN', 'Tamil Nadu'), ('VIZ', 'Vizag'), ('KAR', 'Karnataka')], max_length=7),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='To_location',
            field=models.CharField(choices=[('HYD', 'Hyderabad'), ('MB', 'Mumbai'), ('T', 'Tirupati'), ('ND', 'New Delhi'), ('TN', 'Tamil Nadu'), ('VIZ', 'Vizag'), ('KAR', 'Karnataka')], max_length=7),
        ),
    ]
